structure(list(url = "h/functions/fwa_locatealong/items?blue_line_key=356308001&downstream_route_measure=0&limit=10000&offset=0&bbox=1&nocache=true", 
    status_code = 400L, headers = structure(list(server = "nginx/1.18.0 (Ubuntu)", 
        date = "Thu, 19 Sep 2024 16:31:27 GMT", `content-type` = "text/plain; charset=utf-8", 
        `content-length` = "60", connection = "keep-alive", `content-encoding` = "gzip", 
        vary = "Accept-Encoding", `x-content-type-options` = "nosniff"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.18.0 (Ubuntu)", 
            date = "Thu, 19 Sep 2024 16:31:27 GMT", `content-type` = "text/plain; charset=utf-8", 
            `content-length` = "60", connection = "keep-alive", 
            `content-encoding` = "gzip", vary = "Accept-Encoding", 
            `x-content-type-options` = "nosniff"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("Invalid value for parameter bbox: 1\n"), 
    date = structure(1726763487, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 1.3e-05, 
    connect = 0, pretransfer = 7.7e-05, starttransfer = 0.215811, 
    total = 0.215865)), class = "response")
