structure(list(url = "h/functions/not_a_function/items?blue_line_key=356308001&downstream_route_measure=0&limit=10000&offset=0", 
    status_code = 404L, headers = structure(list(server = "nginx/1.18.0 (Ubuntu)", 
        date = "Fri, 14 Jan 2022 05:42:07 GMT", `content-type` = "text/plain; charset=utf-8", 
        `content-length` = "34", connection = "keep-alive", `content-encoding` = "deflate", 
        vary = "Accept-Encoding", `x-content-type-options` = "nosniff"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.18.0 (Ubuntu)", 
            date = "Fri, 14 Jan 2022 05:42:07 GMT", `content-type` = "text/plain; charset=utf-8", 
            `content-length` = "34", connection = "keep-alive", 
            `content-encoding` = "deflate", vary = "Accept-Encoding", 
            `x-content-type-options` = "nosniff"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("Function not found: not_a_function\n"), 
    date = structure(1642138927, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.8e-05, 
    connect = 3.8e-05, pretransfer = 0.000132, starttransfer = 0.096767, 
    total = 0.096809)), class = "response")
