structure(list(url = "h/collections/whse_basemapping.fwa_lakes_poly/items.json?limit=10000&offset=0&transform=not_a_transform", 
    status_code = 400L, headers = structure(list(server = "nginx/1.18.0 (Ubuntu)", 
        date = "Fri, 14 Jan 2022 05:41:34 GMT", `content-type` = "text/plain; charset=utf-8", 
        `content-length` = "54", connection = "keep-alive", `content-encoding` = "deflate", 
        vary = "Accept-Encoding", `x-content-type-options` = "nosniff"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.18.0 (Ubuntu)", 
            date = "Fri, 14 Jan 2022 05:41:34 GMT", `content-type` = "text/plain; charset=utf-8", 
            `content-length` = "54", connection = "keep-alive", 
            `content-encoding` = "deflate", vary = "Accept-Encoding", 
            `x-content-type-options` = "nosniff"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("Invalid value for parameter transform: not_a_transform\n"), 
    date = structure(1642138894, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.5e-05, 
    connect = 3.5e-05, pretransfer = 0.000163, starttransfer = 0.095257, 
    total = 0.095283)), class = "response")
