structure(list(url = "h/functions/fwa_locatealong/items?blue_line_key=356308001&downstream_route_measure=0&limit=10000&offset=0&bbox=1", 
    status_code = 400L, headers = structure(list(server = "nginx/1.18.0 (Ubuntu)", 
        date = "Fri, 14 Jan 2022 05:42:08 GMT", `content-type` = "text/plain; charset=utf-8", 
        `content-length` = "42", connection = "keep-alive", `content-encoding` = "deflate", 
        vary = "Accept-Encoding", `x-content-type-options` = "nosniff"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.18.0 (Ubuntu)", 
            date = "Fri, 14 Jan 2022 05:42:08 GMT", `content-type` = "text/plain; charset=utf-8", 
            `content-length` = "42", connection = "keep-alive", 
            `content-encoding` = "deflate", vary = "Accept-Encoding", 
            `x-content-type-options` = "nosniff"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("Invalid value for parameter bbox: 1\n"), 
    date = structure(1642138928, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.001323, 
    connect = 0.280108, pretransfer = 0.631089, starttransfer = 0.757626, 
    total = 0.757703)), class = "response")
